### ISSUE TITLE
run subject_extract.py meet the error!

### ISSUE THREAD

**Issue by FakerYFX** [bojone/bert_in_keras#10]
when i run nl2sql_baseline.py , i meet this error:
Traceback (most recent call last):
  File "subject_extract.py", line 47, in <module>
    D = D[D[2] != u'其他']
  File "/home/work/.local/lib/python2.7/site-packages/pandas/core/ops.py", line 1728, in wrapper
    (is_extension_array_dtype(other) and not is_scalar(other))):
  File "/home/work/.local/lib/python2.7/site-packages/pandas/core/dtypes/common.py", line 1749, in is_extension_array_dtype
    registry.find(dtype) is not None)
  File "/home/work/.local/lib/python2.7/site-packages/pandas/core/dtypes/dtypes.py", line 89, in find
    return dtype_type.construct_from_string(dtype)
  File "/home/work/.local/lib/python2.7/site-packages/pandas/core/dtypes/dtypes.py", line 699, in construct_from_string
    raise TypeError(msg.format(string))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
@bojone

**Comment by FakerYFX** [comment]
have solved!
