### ISSUE TITLE
大佬您好，我在调用官方预训练模型，即代码为bert_model = load_trained_model_from_checkpoint(config_path, checkpoint_path, seq_len=None)这一语句时，出现了如下问题，可以请教一下为何吗，谢谢

### ISSUE THREAD

**Issue by 2941894638** [bojone/bert_in_keras#28]
Traceback (most recent call last):
  File "E:\PYTHON36\lib\contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "E:\PYTHON36\lib\site-packages\tensorflow\python\framework\ops.py", line 5652, in get_controller
    yield g
  File "E:\PYTHON36\lib\site-packages\keras\engine\base_layer.py", line 491, in __call__
    arguments=user_kwargs)
  File "E:\PYTHON36\lib\site-packages\keras\engine\base_layer.py", line 559, in _add_inbound_node
    output_tensors[i]._keras_shape = output_shapes[i]
IndexError: list index out of range

**Comment by LiYing22** [comment]
请问解决了吗？我遇到了同样的问题。
